CREATE CAST (character varying AS PRODUCT_STATUS) WITH INOUT AS ASSIGNMENT;
CREATE CAST (character varying AS USER_ROLE) WITH INOUT AS ASSIGNMENT;
CREATE CAST (character varying AS ORDER_STATUS) WITH INOUT AS ASSIGNMENT;